version: '3.8'
services:
  consumet-api:
    image: riimuru/consumet-api
    container_name: consumet-api
    restart: unless-stopped
    ports:
      - "6969:3000"
  m3u8-proxy:
    image: dovakiin0/m3u8-proxy
    container_name: m3u8-proxy
    restart: unless-stopped
    ports:
      - "8080:8080"
  postgres:
    restart: always
    image: postgres:latest
    container_name: better-melon
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: better-melon
    volumes:
      - postgres:/data/postgres/better-melon

volumes:
  postgres: